# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [ ]:
uno = np.zeros(12)
uno

In [ ]:
dos= np.zeros(10)
dos[4]= 10
dos

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
tres= np.array(range(10,50))
tres

In [ ]:
cuatro= np.zeros([3,3])
num=0
for i in range (0,3):
  for j in range (0,3):
    cuatro[i][j]= num
    num=num+1
cuatro

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
cinco= np.random.rand(100)
cinco_media=np.mean(cinco)
cinco_var=np.var(cinco)

0.5555680919871182

In [ ]:
array_uno= np.array([12,12,14])
seis= np.sum(array_uno)/np.shape(array_uno)
seis


array([12.66666667])

In [ ]:
array_uno= np.array([12,12,14])
array_media= np.mean(array_uno)
array_diferencia= (array_uno - array_media) ** 2
siete= np.mean(array_diferencia)
siete


0.888888888888889

In [ ]:
ocho= np.random.randn(10)
ocho

array([-1.36595053, -0.12247078,  0.94957013, -0.0734536 , -0.93351856,
       -0.75314134, -0.52192101,  1.15536104, -0.97814825, -1.68090367])